apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capston-backend
  template:
    metadata:
      labels:
        app: capston-backend
    spec:
      containers:
        - image: rk8sacr.azurecr.io/capston-backend-image:v1
          name: capston-containers
          ports:
            - containerPort: 8000
          env:
          - name: CONNECTION_STRING
            value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:sql-server-capston-cin-001.database.windows.net,1433;Database=sql-db-capston-cin-001;Uid=devops123;Pwd=Devops@1@3#5;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"


